name: Testes

# Gatilhos
on:
  push:
    branches: [ main ]  

jobs:
  build:
  # Máquina ou ambiente que será utilizada nos testes
    runs-on: ubuntu-latest

	# Passos
    steps:
	# Baixa o código para a máquina que está sendo "levantada"
    - uses: actions/checkout@v2

  # Instala o Node.js na versão especificada
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
  # Instala todos os pacotes que estão no arquivo package.json em Dependencies/DevDependencies      
    - run: npm install

    - run: npm run cy:run
      continue-on-error: true # configuração para que os testes continuem rodando mesmo que algum cenário falhe
    
    - run: npm run report:merge
    
    - run: npm run report:mocha

# GitHub Pages - Publicar o relatório
    - name: Deploy to GitHub Pages      
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: mochawesome-report
